---
title: "TARLOC_SPREAD"
#author: "CHENRUJIE"
#date: "2018年9月2日"
output: 
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This script is to identify necessary trading positions of targets and lockers to implement neural risk like strategy which can advoid daily violatility amid tracking the yield trends.

## Identify Multiplyer

```{r Multiplyer}
#Load dataset which is generated by TARLOC main script.
library(readr)
TD_All <- read.csv("C:/Users/crjMo/Desktop/TARLOC/DEEPLEARN/TD_All.csv")

#Define Targets and Locks
ref_Targets <- c("J0")
ref_Locker <- c("T00C2")

#Extract close price of targets and locker.
Dataset.TARLOC <- cbind(TD_All[, paste0(ref_Targets, "Close")],
                        TD_All[, paste0(ref_Locker, "Close")])
#Omit NAs.
Dataset.TARLOC <- na.omit(Dataset.TARLOC)

#Functions to generate pair trading mutiple factor.
Multiple_Factor <- function(alpha_data, alpha_multi,
                            beta_data, beta_multi){
  alpha.rate <- log(alpha_data[2:length(alpha_data)]) - 
    log(alpha_data[1:(length(alpha_data)-1)])
  beta.rate <- log(beta_data[2:length(beta_data)]) - 
    log(beta_data[1:(length(beta_data)-1)])
  #Calculate var and cov
  alpha.var <- var(alpha.rate)
  beta.var <- var(beta.rate)
  covalbe <- cov(alpha.rate, beta.rate)
  #Calculate gamma for alpha and beta
  gama.alpha <- covalbe/alpha.var*beta_multi/alpha_multi
  gama.beta <- covalbe/beta.var*alpha_multi/beta_multi
  multi.beta <- 1/abs(gama.alpha)
  multi.alpha <- 1/abs(gama.beta)
  return(list('alpha.multiplyer' = multi.alpha,
              'beta.multiplyer' = multi.beta))
}

Multiplyer <- Multiple_Factor(Dataset.TARLOC[, 1], 100*0.15, Dataset.TARLOC[, 2], 10000*0.03)
Multiplyer

print(paste("Multiplyer for 10 year treasury is", floor(Multiplyer$beta.multiplyer), "times.", sep = " "))
```

## Pair Trade Spread Analysis

```{r Spread}
#Convert Trade Data into timeseries
library(timeDate)
library(timeSeries)
library(ggplot2)
library(scales)
Spread.TD_All.ts <- timeSeries(TD_All[, -1], as.Date(TD_All$X), format = "%Y-%m-%d")
#Extract Pair
Spread.Dataset.ts <- Spread.TD_All.ts[, paste0(c(ref_Targets, ref_Locker), "Close")]
#Calculate pair trade spread along with format conversion.
if(exists("Spread.Dataset")){
  rm(Spread.Dataset)
}
Spread.Dataset <- as.data.frame(TD_All[, 1])
colnames(Spread.Dataset) <- c("Date")
Spread.Dataset$Spread <- Spread.Dataset.ts$T00C2Close*5*10000*0.03 - Spread.Dataset.ts$J0Close*0.15
#Remove NAs.
Spread.Dataset <- na.omit(Spread.Dataset)
#Result Output.
x_label <- seq.Date(from = as.Date(Spread.Dataset$Date[1]), 
                    to = as.Date(Spread.Dataset$Date[dim(Spread.Dataset)[1]]), by = "2 month")
Spread.gg1 <- ggplot(Spread.Dataset, aes(Date, group = 1)) +
  geom_line(aes(y = Spread), colour = "black") +
  geom_smooth(aes(y = Spread), method = "loess") +
  scale_x_discrete(breaks= c(as.character(x_label)), labels = format(x = x_label, format = "%m-%d"))

Spread.gg1
```

